# Generated by Django 5.0.3 on 2024-06-29 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='film name')),
                ('director', models.CharField(max_length=20, verbose_name='film director')),
                ('release_date', models.DateField(verbose_name='released date')),
                ('now_showing', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningRoom',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='screening room name')),
                ('rows', models.IntegerField()),
                ('columns', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.film')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(verbose_name='screening time')),
                ('ticketPrice', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('ScreeningRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.screeningroom')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.film')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('film', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TicketService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seat_number', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.timeslot')),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='myapi_ticke_user_id_550879_idx')],
            },
        ),
        migrations.CreateModel(
            name='SeatStatus',
            fields=[
                ('ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('seat_number', models.IntegerField()),
                ('is_occupied', models.BooleanField(default=False)),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.timeslot')),
            ],
            options={
                'indexes': [models.Index(fields=['timeslot', 'seat_number'], name='myapi_seats_timeslo_0ce8f9_idx')],
                'unique_together': {('seat_number', 'timeslot')},
            },
        ),
    ]
