# Generated by Django 5.0.3 on 2024-06-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_film_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='time',
            new_name='begin_time',
        ),
        migrations.AlterField(
            model_name='film',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
