# Generated by Django 5.0.3 on 2024-06-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_rename_time_timeslot_begin_time_alter_film_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketservice',
            name='price',
        ),
    ]
